# Site Information
title: "Axcora Framework"
description: "Modern static site generator with built-in CSS framework"
url: "https://ssg.axcora.com"
#url: http://localhost:3000
author: "Axcora Team"
image: "/img/axs.jpg"
logo: "/img/logo.png"
favicon: "/img/logo.jpg"
blog:
  posts_per_page: 6
  show_excerpts: true

show_blog_list: false

search:
  enabled: false

# Theme settings
theme:
  enable_dark_mode: true
  default_theme: "light"


# Social Media
social:
 - name: Github Sponsor
   url: "https://github.com/sponsors/mesinkasir"
 - name: Via Gumroad
   url: "https://creativitaz.gumroad.com/coffee"
 - name: Via Paypal
   url: "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JVZVXBC4N9DAN"
 - name: Via Midtrans
   url: "https://app.midtrans.com/payment-links/1647457988722"


# Navigation Menu
navbar:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Installation" 
    url: "/install/"
  - title: "Templating" 
    url: "/templating/"
  - title: "Components" 
    url: "/components/"
  - title: "CSS" 
    url: "/examples/"
  - title: "Themes" 
    url: "/themes/"
#  - title: "Blog" 
#    url: "/blog/"
#  - title: "Tags"
#    url: "/tags/"
#  - title: "Categories"
#    url: "/categories/"
  - title: "Support"
    url: "/support/"

# SEO Settings
seo:
  keywords: ["static site generator", "css framework", "web development", "responsive design"]
  google_analytics: "GA_TRACKING_ID"
  google_search_console: "SEARCH_CONSOLE_ID"


# Build Settings
build:
  minify_css: true
  minify_js: true
  optimize_images: true
  generate_sitemap: true
  generate_rss: true
